org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1.2
yarn_mappings=26.1.2+build.1
loader_version=0.20.0

fabric_version=0.130.0+26.1.2

mod_version=1.0.0
maven_group=com.example
archives_base_name=ShowFps+

# Verify these versions at https://modrinth.com/mod/cloth-config and https://modrinth.com/mod/modmenu
cloth_config_version=22.0.0
modmenu_version=19.0.0
